image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - docker-compose -f ./docker-compose.yml build
            services:
              - docker
            caches:
              - docker
        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint Dockerfile
  branches:
    master:
      - step:
          name: Push to DockerHub - master
          deployment: Production
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker-compose -f ./docker-compose.yml build
            - docker tag "${DOCKERHUB_USERNAME}/${IMAGE_NAME}" "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:master"
            - docker push "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:master"
          services:
            - docker
    develop:
      - step:
          name: Push to DockerHub - develop
          deployment: Test
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker-compose -f ./docker-compose.yml build
            - docker tag "${DOCKERHUB_USERNAME}/${IMAGE_NAME}" "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:develop"
            - docker push "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:develop"
          services:
            - docker